intz/site/__init__.py
from flask import Blueprint
# from intz import dev_blueprint
import flask_restful


site_blueprint = Blueprint('site',
              __name__,
              template_folder='./templates',
              static_folder='./static',
            static_url_path='/site/static'
)


# dev = flask_restful.Api()
# dev.init_app(site_blueprint)


from . import views

intz/site/views.py
from flask import render_template, request, abort, redirect, url_for, jsonify
from . import site_blueprint
from intz import models, db, login_manager
from flask_login import login_user, login_required, logout_user, current_user
from flask_wtf import Form
from wtforms import StringField, IntegerField
from wtforms.validators import DataRequired, Email
import requests


class LoginForm(Form):
	username = StringField('username', validators=[DataRequired()])
	password = StringField('password', validators=[DataRequired()])


class JoinForm(Form):
	username = StringField('username', validators=[DataRequired()])
	email = StringField('email', validators=[Email(), DataRequired()])
	password = StringField('password', validators=[DataRequired()])
	password_confirm = StringField('password_confirm', validators=[DataRequired()])


# class NewIntegerForm(Form):
# 	integer = IntegerField('value', validators=[DataRequired()])
# 	label = StringField('label', validators=[DataRequired()])


@site_blueprint.route('/login', methods = ['GET', 'POST'])
def login():
	form = LoginForm(csrf_enabled=False)
	next_url = request.args.get('next')

	if current_user.is_authenticated:
		return redirect(next_url or url_for('site.dashboard'))

	if form.validate_on_submit():
		# Get fields from form submission
		username = request.form['username']
		password = request.form['password']

		if username is None or password is None:
			return render_template('login.html')

		# Get supposed user object from database
		user = models.User.query.filter(models.User.username == username).first()

		# Verify credentials
		if user is not None and user.verify_password(password):
			# Login user and commit to database before redirecting (order is important here)
			user.authenticated = True
			db.session.add(user)
			db.session.commit()
			login_user(user, remember=True)

			# Redirect
			next_url = request.args.get('next')
			return redirect(next_url or url_for('site.dashboard'))

	return render_template('login.html')


@site_blueprint.route('/logout')
@login_required
def logout():
	# Logout user and commit to database (order is important here)
	current_user.authenticated = False
	db.session.add(current_user)
	db.session.commit()
	logout_user()

	return redirect(url_for('site.home'))


@site_blueprint.route('/join', methods = ['GET', 'POST'])
def join():
	form = JoinForm(csrf_enabled=False)
	next_url = request.args.get('next')

	if current_user.is_authenticated:
		return redirect(next_url or url_for('site.dashboard'))

	if form.validate_on_submit():
		username = request.form['username']
		email = request.form['email']
		password = request.form['password']
		password_confirm = request.form['password_confirm']

		# TODO: May not need this
		if username is None\
				or email is None\
				or password is None\
				or password_confirm is None:
			return render_template('join.html')  # TODO: Add proper response

		if password != password_confirm or len(password) < 8:
			return render_template('join.html')  # TODO: Add proper response

		# Check for prior existence of username and email
		if db.session.query(db.exists().where(models.User.username == username)).scalar()\
				or db.session.query(db.exists().where(models.User.email == email)).scalar():
			return render_template('join.html')  # TODO: Add proper response

		# Create new user object
		new_user = models.User(username=username, email=email, password=password)

		# Login user and commit to database before redirecting (order is important here)
		new_user.authenticated = True
		db.session.add(new_user)
		db.session.commit()
		login_user(new_user, remember=True)

		return redirect(next_url or url_for('site.dashboard'))

	return render_template('join.html')


@site_blueprint.route('/')
def home():
	next_url = request.args.get('next')

	if current_user.is_authenticated:
		return redirect(next_url or url_for('site.dashboard'))
	else:
		return render_template('index.html')


@site_blueprint.route('/dashboard')
@login_required
def dashboard():
	# form = NewIntegerForm(csrf_enabled=False)
	return render_template('dashboard.html')


@site_blueprint.route('/dashboard/get_all_integers', methods=['GET'])
@login_required
def get_all_integers():
	r = requests.get(url_for('dev.integerlistcontroller'),
					 headers={'Authorization': 'Token ' + current_user.api_key})

	return jsonify({
		'data': r.json()
	})


@site_blueprint.route('/dashboard/new_integer', methods=['POST'])
@login_required
def new_integer():
	next_url = request.args.get('next')

	# form = NewIntegerForm(csrf_enabled=False)

	# if form.validate_on_submit():  # TODO: Get this to freaking work
	value = request.form['value']
	label = request.form['label']

	if value is not None:
		try:
			int(value)
		except ValueError:
			redirect(url_for('site.dashboard'))
	else:
		return redirect(url_for('site.dashboard'))

	data = {
		'value': value,
		'label': label
	}

	requests.post(url_for('dev.integerlistcontroller'),
					 headers={'Authorization': 'Token ' + current_user.api_key},
					 data=data)

	return redirect(next_url or url_for('site.dashboard'))


@site_blueprint.route('/dashboard/delete_integer/<string:int_id>', methods=['POST', 'DELETE'])
@login_required
def delete_integer(int_id):
	next_url = request.args.get('next')

	if int_id is None:
		return redirect(url_for('site.dashboard'))

	requests.delete(url_for('dev.integercontroller', int_id=str(int_id)),
					 headers={'Authorization': 'Token ' + current_user.api_key})

	return '', 204



@site_blueprint.route('/docs')
def docs():
	return render_template('docs.html')


@site_blueprint.route('/new_api_key')
@login_required
def new_api_key():
	r = requests.get('0.0.0.0:7000',
				 headers={'Authorization': 'Token ' + current_user.api_key})

	return jsonify(r.json())


@site_blueprint.route('/current_api_key')
@login_required
def current_api_key():
	r = requests.get(url_for('dev.current_api_key'),
					 headers={'Authorization': 'Token ' + current_user.api_key})

	return jsonify(r.json())



@login_manager.user_loader
def load_user(user_id):
	try:
		return models.User.query.get(user_id)
	except:
		return None

intz/site/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% block head %}
        <meta charset="UTF-8">
        <link rel="stylesheet" href="{{ url_for('site.static', filename='foundation-6.2.3-custom/css/foundation.css') }}">
        <script src="{{ url_for('site.static', filename='foundation-6.2.3-custom/js/vendor/jquery.js') }}"></script>
        <script src="{{ url_for('site.static', filename='foundation-6.2.3-custom/js/vendor/foundation.min.js') }}"></script>
        <link rel="stylesheet" href="{{ url_for('site.static', filename='css/base.css') }}">
        {% endblock %}
    </head>

    <body>
        {% block body %}

        <div data-sticky-container>
            <div class="top-bar sticky" data-sticky data-options="marginTop:0;" style="width:100%">
                <div class="top-bar-left">
                    <div class="leftBarContentContainer">
                        <ul class="menu">
                            <li><a href="{{ url_for('site.home') }}" class="menu-text">Int<span class="blueText">&#x2124;</span>.io</a></li>
                        </ul>
                    </div>
                </div>

                <div class="top-bar-right">
                    <div class="rightBarContentContainer">
                        <ul class="menu">
                            <li><a href="{{ url_for('site.docs') }}" class="button blueOutline fadeToBlue noRightBorder">Docs</a></li>
                            {% if current_user.is_authenticated %}
                            <li><a href="{{ url_for('site.dashboard') }}" class="button blueOutline fadeToBlue noLeftRightBorder">Dashboard</a></li>
                            <li><a href="{{ url_for('site.logout') }}" class="button blueOutline fadeToBlue noLeftBorder">Logout</a></li>
                            {% else %}
                            <li><a href="{{ url_for('site.join') }}" class="button blueOutline fadeToBlue noLeftRightBorder">Join</a></li>
                            <li><a href="{{ url_for('site.login') }}" class="button blueOutline fadeToBlue noLeftBorder">Login</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        {% endblock %}

        <script>
          $(document).foundation();
        </script>

    </body>
</html>

intz/site/templates/dashboard.html
{% extends "base.html" %}

{% block head %}
{{ super() }}

<title>Dashboard</title>

<link rel="stylesheet" href="{{ url_for('site.static', filename='css/dashboard.css') }}">

{% endblock %}


{% block body %}
{{ super() }}

<div class="row align-middle standardDiv">
    <div class="column large-12 align-self-center">
        <h2 class="mainTitle titleText"><span class="blueText">&#x2124;</span> Integers</h2>
    </div>

    <div class="column large-12 align-self-center">
        <div id="newIntegerButton" class="button blueOutline fadeToBlue" data-newinteger="{{ url_for('site.new_integer') }}">New Integer</div>
        <div id="integerContainer" data-getintegersurl="{{ url_for('site.get_all_integers') }}">
            <table border="1">

            </table>
        </div>
    </div>
</div>

<div class="row align-middle standardDiv">
    <div class="column large-12 align-self-center">
        <h2 class="mainTitle titleText"><span class="blueText">&#x2124;</span> API Key</h2>
    </div>

    <div class="column large-12 align-self-center">
        <div id="keyButton" class="button blueOutline fadeToBlue" data-newapikey="{{ url_for('site.new_api_key') }}">Get New Key</div>
        <div id="keyContainer">
            <p data-currentapikey="{{ url_for('site.current_api_key') }}"></p>
        </div>

        <p class="bodyText">
            <span class="blueText">WARNING:</span> Do NOT give out your API key. It provides access to all of your private integers.<br>
        </p>
        <p class="bodyText">
            <span class="blueText">NOTE:</span> Resetting your password will change your API key. This is useful if you think someone else has gained access to your current key.
        </p>
    </div>
</div>

<a href="#" data-reveal-id="myModal">Click Me For A Modal</a>

<div class="reveal" id="newIntegerModal" data-reveal>
    <h3>New Integer</h3>
    <p class="lead greyText">Provide a label and value for your new integer:</p>

    <form method="POST" action="{{ url_for('site.new_integer') }}">
        <h6 class="greyText">Label:</h6>
        <input type="text" name="label"><br>
        <h6 class="greyText">Value:</h6>
        <input type="number" name="value"><br>
        <input class="button blueOutline fadeToBlue" type="submit" value="Create">
    </form>

    <button class="close-button" data-close aria-label="Close modal" type="button">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

<script>
    function displayIntegers(data) {
        integerList = data.integer_list;
        htmlToInsert = "<tr>\
                <th>Label</th>\
                <th>Value</th>\
                <th>ID</th>\
              </tr>";

        for (var i = integerList.length - 1; i >= 0; --i) {
            integer = integerList[i];

            htmlToInsert += "<tr class=\"rowFormat\">\
                <td>" + integer.label + "</td>\
                <td>" + integer.value + "</td>\
                <td id=" + integer.id + ">" + integer.id + "<a class=\"editButton button redOutline fadeToRed\" data-deleteintegerurl=\"{{ url_for('site.delete_integer', int_id=placeholder) }}\" onclick=\"deleteInteger(this);\">Delete</a></td>\
              </tr>";
        }

        $("#integerContainer table").html(htmlToInsert);
    }

    function getAllIntegers() {
        // Display all of the user's integers
        var integersURL = $("#integerContainer").data("getintegersurl");

        $.get(integersURL, function(data, status){
            displayIntegers(data.data);
        });
    }

    function getCurrentAPIKey(callback) {
        // Display user's current API key
        var currentApiKeyURL = $("#keyContainer p").data("currentapikey");

        $.get(currentApiKeyURL, function(data, status){
            $("#keyContainer p").html(data.api_key);
            callback(data);
        });
    }

    $(document).ready(function() {
        getCurrentAPIKey(function(data){
            getAllIntegers();  // This has to be in a callback in case it's a first time user and they don't have an API key, yet
        });
    });



    $("#keyButton").click(function() {
        var newApiKeyURL = $("#keyButton").data("newapikey");

        $.get(newApiKeyURL, function(data, status){
            $("#keyContainer p").html(data.api_key);
        });
    });

    $("#newIntegerButton").click(function() {
        var popup = new Foundation.Reveal($('#newIntegerModal'));
        popup.open();
    });

    function deleteInteger(deleteButton) {
        var deleteIntegerURL = $(deleteButton).data("deleteintegerurl") + deleteButton.parentNode.id;

        $.delete(deleteIntegerURL, function(data, status){
            rowToDelete = deleteButton.parentNode.parentNode;
            rowToDelete.parentNode.removeChild(rowToDelete);
        });
    }


    $.delete = function(url, callback){
        $.ajax({
            url: url,
            type: 'DELETE',
            data: {},
            contentType:'application/json',
            dataType: 'text',
            success: callback
        });
    }
</script>

{% endblock %}

intz/site/templates/docs.html
{% extends "base.html" %}

{% block head %}
{{ super() }}

<title>Docs</title>

<link rel="stylesheet" href="{{ url_for('site.static', filename='css/docs.css') }}">

{% endblock %}


{% block body %}
{{ super() }}

    <div class="row align-middle standardDiv">
        <div class="column large-12 align-self-center">
            <h2 class="mainTitle titleText"><span class="blueText">&#x2124;</span> Using Intz.io</h2>
        </div>

        <div class="column large-12 align-self-center">
            <p class="bodyText">
                Intz.io implements a simple RESTful API designed to easily allow you to store and retrieve your integers. Integers have the following format:<br>
                {<br>
                    <span class="integerJSON">id: "77671624-9dfa-37d3-b459-abf9eae34317"</span>,<br>
                    <span class="integerJSON">label: "my_integer"</span>,<br>
                    <span class="integerJSON">value: 700<br></span>
                }
            </p>

            <p class="bodyText">You can query integers by <span class="blueText">id</span>, <span class="blueText">label</span>, <span class="blueText">value</span>, or any combination therein. Consuming the Int.z API using cURL is simple:</p>
        </div>
    </div>

    <div class="row align-middle standardDiv">
        <div class="column large-12 align-self-center">
            <p class="bodyText">
                <span class="requestGET">GET</span> a list all of your integers<br>
                <span class="code">curl -H http://dev.intz.io/integers "Authorization: Token AUTH_TOKEN"</span>
            </p>
            <p class="bodyText">
                <span class="requestGET">GET</span> an integer by <span class="blueText">id</span><br>
                <span class="code">curl -H http://dev.intz.io/integers/<span class="blueText">id</span> "Authorization: Token AUTH_TOKEN"</span>
            </p>
            <p class="bodyText">
                <span class="requestGET">GET</span> a list of integers by <span class="blueText">value</span> and/or <span class="blueText">label</span><br>
                <span class="code">curl -H http://dev.intz.io/integers -X GET -d "<span class="blueText">value</span>=700" -d "<span class="blueText">label</span>=my_integer" "Authorization: Token AUTH_TOKEN"</span>
            </p>
            <p class="bodyText">
                <span class="requestPOST">POST</span> an integer with a <span class="blueText">value</span> and/or <span class="blueText">label</span><br>
                <span class="code">curl -H http://dev.intz.io/integers -X POST -d "<span class="blueText">value</span>=700" -d "<span class="blueText">label</span>=my_integer" "Authorization: Token AUTH_TOKEN"</span>
            </p>
            <p class="bodyText">
                <span class="requestPUT">PUT</span> to update an integer by <span class="blueText">id</span> with a new <span class="blueText">value</span> and/or <span class="blueText">label</span><br>
                <span class="code">curl -H http://dev.intz.io/integers/<span class="blueText">id</span> -X PUT -d "<span class="blueText">value</span>=700" -d "<span class="blueText">label</span>=my_integer" "Authorization: Token AUTH_TOKEN"</span>
            </p>
            <p class="bodyText">
                <span class="requestPUT">PUT</span> to update a list of integers filtered by <span class="blueText">value</span> and/or <span class="blueText">label</span> with <span class="blueText">newValue</span> and/or <span class="blueText">newLabel</span><br>
                <span class="code">curl -H http://dev.intz.io/integers -X PUT -d "<span class="blueText">value</span>=700" -d "<span class="blueText">label</span>=my_integer" <span class="blueText">newValue</span>=1000" -d "<span class="blueText">newLabel</span>=her_integer "Authorization: Token AUTH_TOKEN"</span>
            </p>
            <p class="bodyText">
                <span class="requestDELETE">DELETE</span> an integer by <span class="blueText">id</span><br>
                <span class="code">curl -H http://dev.intz.io/integers/<span class="blueText">id</span> -X DELETE "Authorization: Token AUTH_TOKEN"</span>
            </p>
            <p class="bodyText">
                <span class="requestDELETE">DELETE</span> a list of integers by <span class="blueText">value</span> and/or <span class="blueText">label</span><br>
                <span class="code">curl -H http://dev.intz.io/integers -X DELETE <span class="blueText">value</span>=700" -d "<span class="blueText">label</span>=my_integer" "Authorization: Token AUTH_TOKEN"</span>
            </p>
        </div>
    </div>

{% endblock %}

intz/site/templates/index.html
{% extends "base.html" %}

{% block head %}
{{ super() }}

<title>Home</title>

<link rel="stylesheet" href="{{ url_for('site.static', filename='css/index.css') }}">

{% endblock %}


{% block body %}

    <!--{% if current_user.is_authenticated %}-->
        <!--Hi {{ current_user.username }}!-->
    <!--{% else %}-->
        <!--Hello, and welcome to IAAS!-->
    <!--{% endif %}-->

    <section class="hero">
        <div class="row intro">
            <div class="small-centered medium-uncentered medium-6 large-7 columns">
              <h1>Too many integers?</h1>
              <p>IntZ.io is your one stop storage solution for all (&forall;) of your integers (&#x2124;).</p>
            </div>
            <div class="small-centered medium-uncentered medium-6 large-5 columns">
              <div class="logo">&#x2124;</div>
            </div>
            <div class="small-centered medium-uncentered medium-12 large-12 columns">
                <div class="buttonWrapper">
                    <a href="{{ url_for('site.login') }}" class="button whiteOutline fadeToBlue">Login</a>
                    <a href="{{ url_for('site.join') }}" class="button whiteOutline fadeToBlue">Join</a>
                </div>
            </div>
        </div>
    </section>


{% endblock %}

intz/site/templates/join.html
{% extends "base.html" %}


{% block head %}
{{ super() }}

<title>Join</title>
<link rel="stylesheet" href="{{ url_for('site.static', filename='css/join.css') }}">

{% endblock %}


{% block body %}
{{ super() }}

<div id="joinLayout" class="row fullWidth align-middle">

    <div id="form" class="column large-5">
        <h2 class="title">Join</h2>
        <form method="POST" action="/join">
            <h6 class="inputTitle">Username:</h6>
            <input type="text" name="username"><br>
            <h6 class="inputTitle">Email:</h6>
            <input type="email" name="email"><br>
            <h6 class="inputTitle">Password:</h6>
            <input type="password" name="password"><br>
            <h6 class="inputTitle">Confirm Password:</h6>
            <input type="password" name="password_confirm"><br>
            <input class="button" type="submit" value="Submit">
        </form>
        <a href="{{ url_for('site.login') }}" class="button ">Login</a>
    </div>

    <div id="sideBanner" class="column large-7">
        <div class="row align-middle">
            <div class="column large-12">
                <h1 class="bannerText">Your &#x2124;,<br>in the cloud</h1>
            </div>
        </div>
    </div>

</div>

{% endblock %}

intz/site/templates/login.html
{% extends "base.html" %}


{% block head %}
{{ super() }}

<title>Login</title>
<link rel="stylesheet" href="{{ url_for('site.static', filename='css/login.css') }}">

{% endblock %}


{% block body %}
{{ super() }}

<div id="loginLayout" class="row fullWidth align-middle">
    <div class="column large-4 banner">
        <div class="row align-middle">
            <div class="column large-12">
                <h1 class="bannerText">{11, 23, ...</h1>
            </div>
        </div>
    </div>

    <div id="form" class="column large-4">
        <h2 class="title">Login</h2>
        <form method="POST" action="/login">
            <h6 class="inputTitle">Username:</h6>
            <input type="text" name="username"><br>
            <h6 class="inputTitle">Password:</h6>
            <input type="password" name="password"><br>
            <input class="button" type="submit" value="Submit">
        </form>
        <a href="{{ url_for('site.join') }}" class="button">Join</a>
    </div>

    <div class="column large-4 banner">
        <div class="row align-middle">
            <div class="column large-12">
                <h1 class="bannerText">... , 19, 17}</h1>
            </div>
        </div>
    </div>
</div>

{% endblock %}